kind: Service
apiVersion: v1
metadata:
  name: rhvconfigurator
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP 
  ports:
    - port: 8080
      targetPort: 80	
  selector:
    app: rhvconfigurator


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhvconfigurator
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: rhvconfigurator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rhvconfigurator
    spec:
      containers:
      - image: trilio/tvr-configurator-ui:1.0.5
        name: rhvconfigurator
        #command: ["nginx", "-g", "daemon off;"]
        ports:
        - containerPort: 80
          name: rhvconfigurator
      imagePullSecrets:
        - name: regcred-trilio

